<h1>NumPy (Numerical Python)</h1>
<p><em><b>Manual de Referencia NumPy:</b> <a href="https://numpy.org/doc/stable/numpy-ref.pdf">https://numpy.org/doc/stable/numpy-ref.pdf</a></em></p>
<p>Es una librería de Python que provee una serie de métodos para realizar operaciones matemáticas sobre una estructura de datos en forma de matriz (llamado <b>array</b>), que puede ser uni-dimensional (arreglo), bi-dimensional (matriz) o n-dimensional (tensores).</p>
<center><img src="img/numpy1.png"></center>
<p>Un array NumPy es un paquete de matrices N-dimensional que tienen forma de filas y columnas, en la que tenemos varios elementos que están almacenados en sus respectivas ubicaciones de memoria.</p>

<h2>Instalación</h2>
<p>Al trabajar en un entorno local, debemos instalar el paquete NumPy. <b>Recordá crear un entorno virtual previamente.</b> Si estamos trabajando en entornos tipo notebook, no necesitamos instalar ningún paquete para trabajo con datos (NumPy, PanDas, Matplotlib, etc.), sólo necesitamos importarlos.</p>


In [1]:
!pip install numpy


[notice] A new release of pip is available: 23.0.1 -> 25.2
[notice] To update, run: pip install --upgrade pip


<h2>Importando la librería</h2>

In [1]:
import numpy as np
from scipy import stats

lista_nros = [12,12,14,15,16,16,16,20,2,3,4,5,5,7,8,10,22,22]

Para poder manipular mi lista [] con numpy, necesito convertirla en un ARREGLO o VECTOR
Voy a usar el método array() de numpy y le voy a pasar como parámetro la lista
Como le puse un alias a mi numpy importado (np), lo voy a usar para invocar a este método de ahora en adelante

In [2]:
array_nros = np.array(lista_nros)
print(type(array_nros), array_nros) # misma distribución que la lista, pero es matriz
print(type(lista_nros), lista_nros)

<class 'numpy.ndarray'> [12 12 14 15 16 16 16 20  2  3  4  5  5  7  8 10 22 22]
<class 'list'> [12, 12, 14, 15, 16, 16, 16, 20, 2, 3, 4, 5, 5, 7, 8, 10, 22, 22]


<h2>Medidas de tendencia central en NumPy</h2>
<p>En estadística, las medidas de tendencia central son valores que intentan resumir un conjunto de datos en un solo número, representando el "centro" o el valor típico de ese conjunto. Las tres más importantes son la media, la mediana y la moda.</p>
<h3>Media o promedio</h3>
<p>La media es el valor promedio de un conjunto de datos. Se calcula sumando todos los valores y dividiendo por el número de valores.</p>


In [3]:
array_nros = np.array([5,5,5,7,8,10,12,12,14,15,16,16,16,20,2,2,2,3,4,22,22])
media = np.mean(array_nros)
print(f"Promedio/Media: {media}")
print(f"Promedio/Media: {media:.2f}") # formato de 2 decimales con :.2f

Promedio/Media: 10.380952380952381
Promedio/Media: 10.38


### Mediana

La mediana es el valor que se encuentra justo en el medio de un conjunto de datos, una vez que ha sido ordenado de menor a mayor.

¿Cómo se calcula? Primero, ordena todos los valores de menor a mayor.

Encuentra el valor del centro. En caso de que la cantidad de elementos sea par, se realiza el proemedio de ambos valores.

In [4]:
mediana = np.median(array_nros)
print(f"Mediana: {mediana}")


Mediana: 10.0


### Moda

Me devuelve un objeto de tipo ModeResult(array_con_el_primer_valor_que_encuentra, recuento_de_apariciones)
Sólo devuelve la primera ocurrencia en un vector ORDENADO si hay más valores, los ignora 

In [ ]:
moda = stats.mode(array_nros)
print("Moda:", moda)

## Medidas de posición

 Las medidas de posición te dicen dónde se encuentra un dato en relación con el resto del conjunto ordenado.

### Cuartiles

 Los cuartiles son el tipo más común de medida de posición. Son los tres valores que dividen un conjunto de datos ordenados en cuatro partes iguales, donde cada parte contiene el 25% de los datos.

CUARTILES --> numpy.quantile(datos, q)

In [5]:
q1 = np.quantile(array_nros, 0.25)
q2 = mediana
q3 = np.quantile(array_nros, 0.75)

print(f"Q1 = {q1} - Q2 = {q2} - Q3 = {q3}")


Q1 = 5.0 - Q2 = 10.0 - Q3 = 16.0


### Percentil

Un percentil es un valor que divide un conjunto de datos ordenados en 100 partes iguales. El percentil k indica el valor por debajo del cual se encuentra un k por ciento de las observaciones.

In [6]:
# la muestra en 100 => trabaja con porcentajes
# método percentile(arreglo, cuántos elementos tomar)
p60 = np.percentile(array_nros, 60)
p20 = np.percentile(array_nros, 20)
p50 = np.percentile(array_nros, 50)

print("Percentil 60:", p60) # el 60% de los datos ---> menor que q3, que es el 75%
print("Percentil 20:", p20) # el 20% de los datos ---> menor que q1, que es el 25%
print("Percentil 50:", p50) # el 50% de los datos ---> coincide ocnla mediana



Percentil 60: 12.0
Percentil 20: 4.0
Percentil 50: 10.0


## Medidas de variabilidad o dispersión

### Varianza

La varianza es una medida de dispersión que indica qué tan dispersos están los datos en relación con la media. Matemáticamente, la varianza se define como el promedio de los cuadrados de las diferencias entre cada valor y la media del conjunto de datos.
En NumPy, la varianza se puede calcular utilizando el método `var()`.

In [8]:
varianza = np.var(array_nros)
print(f"Varianza: {varianza}")
print(f"Varianza: {varianza:.2f}")


Varianza: 43.188208616780045
Varianza: 43.19


### Desvío Estándar

Es la raíz cuadrada de la varianza

In [9]:
desvio_std = np.std(array_nros)
print(f"Desvío stardard: {desvio_std:.2f}")
print(desvio_std**2)

Desvío stardard: 6.57
43.188208616780045


<h2>Creando estructuras de datos con NumPy</h2>

Los arreglos en Numpy tienen que tener <b>sí o sí</b> los mismos tipos de datos -> los diferencia de las listas Py.

A los elementos de un vector se accede como a lo de los iterables conocidos -> con índice.

Les puedo aplicar slicing.

In [10]:
# CREAR ARREGLOS = ARRAY = VECTOR -> 1 fila, n columnas
# MATRIZ UNIDIMENSIONAL
arr = np.array([99,5,5,5,7,8,10,12,33,56,123,234,12,14,15,16,16,16,20,2,2,2,3,4,22,22,1000])
print('Primer elemento:', arr[0] )
print('Último elemento:', arr[-1])


Primer elemento: 99
Último elemento: 1000


In [11]:
# CREAMOS UNA MATRIZ = ARREGLO BI-DIMENSIONAL
dosd = [[1,10,2],[9,3,5]]
print(f'Lista\n {dosd}')
print()

dosda = np.array(dosd)
print(f'Arreglo numpy\n {dosda}' )
print(type(dosda))

# ACCEDIENDO A LOS VALORES DE LA MATRIZ --> coordenadas[fila, columna]
print(dosda[0,1])
print(dosda[0][1])


Lista
 [[1, 10, 2], [9, 3, 5]]

Arreglo numpy
 [[ 1 10  2]
 [ 9  3  5]]
<class 'numpy.ndarray'>
10
10


In [12]:
# En un array los datos deben ser homogéneos
lv = [1, 'hora', 0.5, True]
array_lv = np.array(lv)
print(array_lv)

['1' 'hora' '0.5' 'True']


<h4>ACTIVIDAD</h4>
<ul><li>Crear dos listas con datos de tipo homogéneo.</li>
<li>Una de las listas -> convertirla a vector</li>
<li>La otra -> convertirla a una matriz de 3 filas x 4 columnas</li></ul>

In [13]:
lista_1 = [2, 3, 5, 7, 11, 13, 17, 19]
lista_2 = [[2, 3, 5, 7], [1, 4, 6, 8],[1, 4, 6, 8]]
np.array(lista_1)


<module 'numpy' from '/root/venv/lib/python3.9/site-packages/numpy/__init__.py'>

In [14]:
np.array(lista_2)

array([[2, 3, 5, 7],
       [1, 4, 6, 8],
       [1, 4, 6, 8]])

<h3>Forzando el tipo de dato</h3>

In [15]:
array1 = np.array([[1.5,2,3,4],[5,6,7,8]]) # dtype
array2 = np.array([[1.5,2,3,4],[5,6,7,8]], dtype=np.int64) 

print(array1)
print()
print(array2)

[[1.5 2.  3.  4. ]
 [5.  6.  7.  8. ]]

[[1 2 3 4]
 [5 6 7 8]]


<h3>Arreglos vacíos</h3>
<p>A veces se crean arreglos vacíos, para luego ser rellenados.</p>
<p>Se inicializan con unos, ceros, valores espaciados uniformemente, valores constantes o valores aleatorios. </p>

In [8]:
# arreglo de unos --> float
unos = np.ones(3)
unos2 = np.ones((4,5)) # doble paréntesis
unos3 = np.ones((4,5), dtype=np.int64) # enteros

print("Vector 1x3:\n", unos)
print("\nMatriz 4x5:\n", unos2)
print("\nMatriz 4x5:(int)\n", unos3)

Vector 1x3:
 [1. 1. 1.]

Matriz 4x5:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Matriz 4x5:(int)
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [17]:
# arreglo de ceros 
unos = np.zeros(3)
unos2 = np.zeros((4,5)) # doble paréntesis
unos3 = np.zeros((4,5), dtype=np.int64) # enteros

print(unos)
print()
print(unos2)
print()
print(unos3)

[0. 0. 0.]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


### Random
arreglo de nros aleatorios  --> método random

In [18]:
# SUBMÉTODO random() --> nro aleatorio entre 0 y 1
a1 = np.random.random(3)
print(a1)
print()
a2 = np.random.random((3,5))
print(a2)
print()
# SUBMÉTODO randint()
a3 = np.random.randint(1,6,5) # random.randint(mínimo, máximo(-1), cantidad)
print(a3)
print()
a4 = np.random.randint(1,6,(4,5))
print(a4)

[0.31136313 0.58518662 0.52507419]

[[0.83669721 0.91384685 0.16698118 0.79840867 0.38991426]
 [0.96764484 0.35957037 0.28726943 0.52212747 0.22278395]
 [0.73579964 0.93315786 0.66146461 0.17440003 0.46099626]]

[5 2 5 2 4]

[[2 5 1 2 1]
 [5 2 2 1 2]
 [4 3 4 2 5]
 [5 3 4 2 2]]


In [19]:
# llena todo el arreglo con el mismo valor
ochos = np.full((4,5), 8)
print(ochos)
print()
mochos = np.full((4,5), 'hola')
print(mochos)
print()
tochos = np.full((4,5), True)
print(tochos)

[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]

[['hola' 'hola' 'hola' 'hola' 'hola']
 ['hola' 'hola' 'hola' 'hola' 'hola']
 ['hola' 'hola' 'hola' 'hola' 'hola']
 ['hola' 'hola' 'hola' 'hola' 'hola']]

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


Para crear arreglos con valores espaciados uniformemente podemos utilizar np.arange() y np.linspace()


In [20]:
# np.arange(): deseo crear un arreglo con los valores comprendidos entre 0 y 100 a paso 5
esp1 = np.arange(0,101,5)
print(esp1)
print()
# np.linspace(): deseo crear 5 valores que se encuentren entre 0 y 2
# esp2 = np.arange(0,2.1,0.5) 
esp2 = np.linspace(0,2,5) # linspace(inicio, tope(entra), cantidad)
print(esp2)
# np.linspace(min, max, n) me divide el rango en min-max en n partes y llena el arreglo con los valores que me da la división
 

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]

[0.  0.5 1.  1.5 2. ]


<h3>Matriz identidad</h3>

In [21]:
mi = np.eye(4)
print(mi)
print()
mi2 = np.eye(4, dtype=np.int64)
print(mi2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


<h3>Inspeccionar arreglos</h3>


In [22]:
arreglo = np.array([(1, 3, 5, 6), (91, True, 1, 4), (1, 1, 1, 1)]) #cambie dos valores True y el float
print(arreglo.shape) # info de filas, columnas
print(type(arreglo))
print(arreglo.dtype) # tipo de dato
print(arreglo.size)


(3, 4)
<class 'numpy.ndarray'>
int64
12


<h3>Cambio de tamaño y forma</h3>

In [23]:
# Sólo puedo darle la forma que se ajuste a la cantidad de elementos que me tira el atributo size
m1 = np.array([(8,9,10),(11,12,13)])
print(m1)
print()
m2 = m1.reshape(3,2)
print(m2)
print()
m3 = m1.reshape(1,6)
print(m3)
print()
m4 = m1.reshape(6,1)
print(m4)
print()


[[ 8  9 10]
 [11 12 13]]

[[ 8  9]
 [10 11]
 [12 13]]

[[ 8  9 10 11 12 13]]

[[ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]]



<h3>Operaciones matemáticas</h3>

In [24]:
a = np.arange(4)
print(a)
b = a*.21
print(b)
c = a+b
print(c)
# aplica para las operaciones -, /,//, **, %

[0 1 2 3]
[0.   0.21 0.42 0.63]
[0.   1.21 2.42 3.63]


<h3>Universal functions (ufunc)</h3>
https://www.w3schools.com/python/numpy/numpy_ufunc.asp También ejecutan una operación elemento a elemento sobre un arreglo Reemplazan los operadores individuales. Son funciones nativas

Ejemplos:
<ul><li>np.add(vector,4) # suma 4</li>
<li>np.substract(vector,2) # resta 2</li>
<li>np.multiply</li>
<li>np.floor_divide(vector,3) # devuelve la division entera</li>
<li>np.negative(vector)</li>
<li>np.power(vector,2) #potencia</li>
<li>np.mod(vector,2)</li></ul>

In [25]:
vector = np.array([(8, 9, 10), (11, 12, 13)])
print(vector.min())
print(vector.max())
print(vector.sum())
print(np.sqrt(vector)) # raíz cuadrada
print(np.std(vector)) # desvío std
print(np.negative(vector)) # negativos
print(np.power(vector, 3)) # función **
print(np.mod(vector,2)) # función %

8
13
63
[[2.82842712 3.         3.16227766]
 [3.31662479 3.46410162 3.60555128]]
1.707825127659933
[[ -8  -9 -10]
 [-11 -12 -13]]
[[ 512  729 1000]
 [1331 1728 2197]]
[[0 1 0]
 [1 0 1]]


<h3>Método append</h3>
Para agregar filas o columnas

In [26]:
mi_array = np.array(([1,4,19,10,5],[3,9,10,8,8]))
e = ([0,0,0,0,0],[1,1,1,1,1])

In [27]:
# MÉTODO APPEND: ARRAY ORIGINAL +  2 FILAS EXTRA
# axis=0 agrega filas
print(mi_array)
print()
arr2 = np.append(mi_array, e, axis = 0)
print(arr2)

[[ 1  4 19 10  5]
 [ 3  9 10  8  8]]

[[ 1  4 19 10  5]
 [ 3  9 10  8  8]
 [ 0  0  0  0  0]
 [ 1  1  1  1  1]]


In [28]:
# MÉTODO APPEND: ARRAY ORIGINAL + 5 COLUMNAS EXTRA
arr3 = np.append(mi_array, e, axis = 1)
print(arr3)


[[ 1  4 19 10  5  0  0  0  0  0]
 [ 3  9 10  8  8  1  1  1  1  1]]


<h3>Repaso de acceso a los elementos y slicing</h3>
Para obtener fragmentos de nuestros sets de datos.

In [ ]:
a = np.array([[1,0,3],[4,3,5],[6,10,-1]])
print(a)


Acceder al 10 (recuerdo que las posiciones empiezan a contarse desde 0)

In [30]:
print(a[2,1])
print()
print(a[1:,1:]) # desde la fila 1, y desde la columna 1


10

[[ 3  5]
 [10 -1]]


In [31]:
# recordemos que si estamos en un array de una sola dimensión, ponemos únicamente 
# el índice que corresponde al elemento que buscamos y listo!
a2 = np.array([25, 36, 10, 85, 56])
print(f"elemento 2 {a2[2]}")
print(f"elemento hasta el ':2'{a2[:2]}")
print(f"elemento ultimo(-1) {a2[-1]}")



elemento 2 10
elemento hasta el ':2'[25 36]
elemento ultimo(-1) 56


In [32]:
# SLICING TOTAL -> Para obtener todos los elementos
a2 = np.array([25, 36, 10, 85, 56])
print(a2[:])
print(a2[::2]) # se queda con los elementos de 2 en 2 posiciones

[25 36 10 85 56]
[25 10 56]


Puedo usar RANGOS de búsqueda, usando el mismo formato <code><mark>inicio:tope:paso</mark></code> de range.
Supongamos que quiero obtener los datos de las celdas:
<ul><li>naranja</li>
<li>turquesa</li>
<li>rojo</li>
<li>verde</li></ul>
<center><img src='img/slicing.png'></center>