# Procesamiento del Habla
----
## Práctica N°3

En esta práctica se trabajará con dos archivos de textos, uno de Benedetti y el otro de Neruda.

## Importación de librerías

In [81]:
import numpy as np
import matplotlib.pyplot as plt
import string
from sklearn.model_selection import train_test_split

Cargamos los archivos de texto


In [82]:
archivos = [
  'Benedetti.txt',
  'Neruda.txt',
]

In [83]:
for f in archivos:
    with open(f, 'r', encoding='utf-8') as ft:
        texto = ft.read()
    print(f"Archivo: {f}\n\nTexto:{texto}")

Archivo: Benedetti.txt

Texto:Poemas varios
Mario Benedetti

La buena tiniebla
Una mujer desnuda y en lo oscuro
genera un resplandor que da confianza
de modo que si sobreviene
un apagón o un desconsuelo
es conveniente y hasta imprescindible
tener a mano una mujer desnuda
entonces las paredes se acuarelan
el cielo raso se convierte en cielo
las telarañas vibran en su ángulo
los almanaques dominguean
y los ojos felices y felinos
miran y no se cansan de mirar
una mujer desnuda y en lo oscuro
una mujer querida o a querer
exorcisa por una vez la muerte.

Preliminar del miedo
Por sobre las terrazas alunadas
donde se aman cautelosamente los gatos
y los brillos esquivan las chimeneas
creo que nadie sabe lo que yo sé esta noche
algo aprendido a pedacitos y a pulsaciones
y que integra mi pánico tradicional modesto
¿cómo desmenuzar plácidamente el miedo
comprender por fin que no es una excusa
sino un escalofrío parecido al disfrute
sólo que amarguísimo y si atenuantes?
los suicidas no tienen prob

## Creamos etiquetas
Vamos a trabajar con etiquetas numéricas para más adelante poder separar lo que el texto que corresponde a cada autor.

In [84]:
textos = []
etiquetas = []

In [85]:
for etiqueta, f in enumerate(archivos):
    print(f"Archivo: {f} -> Corresponde a  etiqueta: {etiqueta}")

Archivo: Benedetti.txt -> Corresponde a  etiqueta: 0
Archivo: Neruda.txt -> Corresponde a  etiqueta: 1


In [86]:
contador = 0
for etiqueta, f in enumerate(archivos):
    with open(f, 'r', encoding='utf-8') as archivo:
        for line in archivo:
            line_l = line.rstrip().lower()
            if line:
                # eliminar puntuación
                line_lp = line_l.translate(str.maketrans('', '', string.punctuation))
                textos.append(line_lp)
                etiquetas.append(etiqueta)
                if contador < 10:
                  print(f"original: {line}")
                  print(f"final: {line_lp}")
                contador +=1


original: Poemas varios

final: poemas varios
original: Mario Benedetti

final: mario benedetti
original: 

final: 
original: La buena tiniebla

final: la buena tiniebla
original: Una mujer desnuda y en lo oscuro

final: una mujer desnuda y en lo oscuro
original: genera un resplandor que da confianza

final: genera un resplandor que da confianza
original: de modo que si sobreviene

final: de modo que si sobreviene
original: un apagón o un desconsuelo

final: un apagón o un desconsuelo
original: es conveniente y hasta imprescindible

final: es conveniente y hasta imprescindible
original: tener a mano una mujer desnuda

final: tener a mano una mujer desnuda


In [87]:
print(f"Textos: {textos[:5]}\n\nLongitud: {len(textos)}")

Textos: ['poemas varios', 'mario benedetti', '', 'la buena tiniebla', 'una mujer desnuda y en lo oscuro']

Longitud: 2100


In [88]:
print(f"Etiquetas: {etiquetas}\nLongitud: {len(etiquetas)}")

Etiquetas: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

## Separación Train y Test

In [89]:
train_text, test_text, Ytrain, Ytest = train_test_split(textos, etiquetas, test_size=0.2, random_state=42)

In [90]:
len(Ytrain), len(Ytest)

(1680, 420)

In [91]:
# train_text
"""
['quizá fue una hecatombe de esperanzas',
 'y el entusiasmo pobre y la condena',
 'todavía',
 'y llena de las vidas del fuego',
 'rescató un relojito que atrasaba',
 'paciencias estiradas',
 '\x0cpoema 8',
 'cuando ames',
 'después ella besó sus labios',
 'se encendía un pedazo de sol entre mis manos',
 ...
 """

"\n['quizá fue una hecatombe de esperanzas',\n 'y el entusiasmo pobre y la condena',\n 'todavía',\n 'y llena de las vidas del fuego',\n 'rescató un relojito que atrasaba',\n 'paciencias estiradas',\n '\x0cpoema 8',\n 'cuando ames',\n 'después ella besó sus labios',\n 'se encendía un pedazo de sol entre mis manos',\n ...\n "

In [92]:
# test_text
"""
['hasta que empiecen a caer las hojas secas',
 'compañera',
 'pero igual me sorprendo',
 '',
 'anuncios y matices',
 'sin embargo alguna vez corrió una sombra extraña por tus ojos',
 'nueve vaya a saber quién es el fuerte',
 'ultima noción de laura',
 '\x0crabia portátil',
 'huracanes de sueños aún a veces las tumban',
 'y una canción desesperada',
 ...
"""

"\n['hasta que empiecen a caer las hojas secas',\n 'compañera',\n 'pero igual me sorprendo',\n '',\n 'anuncios y matices',\n 'sin embargo alguna vez corrió una sombra extraña por tus ojos',\n 'nueve vaya a saber quién es el fuerte',\n 'ultima noción de laura',\n '\x0crabia portátil',\n 'huracanes de sueños aún a veces las tumban',\n 'y una canción desesperada',\n ...\n"

In [93]:
print(f"Elementos del conjunto test/prueba Y: {Ytest[:10]}.\nLongitud: {len(Ytest)}, tipo de dato: {type(Ytest)}")

Elementos del conjunto test/prueba Y: [0, 0, 0, 0, 0, 1, 0, 0, 0, 1].
Longitud: 420, tipo de dato: <class 'list'>


## Construcción de un Diccionario de Codificación de Palabras a Índices

In [94]:
"""
"<unk>" es una convención que se utiliza a menudo en el procesamiento de lenguaje natural para representar palabras
desconocidas o fuera del vocabulario. En este caso, se está asignando el índice 0 a esta palabra especial.
"""
indice = 1
indicepalabras = {'<unk>': 0}

In [95]:
indicepalabras

{'<unk>': 0}

In [96]:
for texto in train_text:
    tokens = texto.split()
    for token in tokens:
        if token not in indicepalabras:
            indicepalabras[token] = indice
            indice += 1

'sin tanta cortedad',
 'la de ella',

In [97]:
# indicepalabras
"""
'paráfrasis': 621,
 'r': 622,
 'tagore': 623,
 'vendamos': 624,
 'llegan': 625,
 'augurios': 626,
 'concurrieron': 627,
 'teatro': 628,
 'otro': 629,
 'será': 630,
 'ix': 631,
 'memoria': 632,
 'caos': 633,
 'pesadillas': 634,
 'venir': 635,
 'reclamarte': 636,
 """

"\n'paráfrasis': 621,\n 'r': 622,\n 'tagore': 623,\n 'vendamos': 624,\n 'llegan': 625,\n 'augurios': 626,\n 'concurrieron': 627,\n 'teatro': 628,\n 'otro': 629,\n 'será': 630,\n 'ix': 631,\n 'memoria': 632,\n 'caos': 633,\n 'pesadillas': 634,\n 'venir': 635,\n 'reclamarte': 636,\n "

In [98]:
len(indicepalabras)

2490

## Transformar los valores del train y test
Convertir el texto a numeros, según el indice de 'indicepalabras'

In [99]:
# convert datos en enteros
train_text_int = []
test_text_int = []

Uso del diccionario previamente creado

In [100]:
for texto in train_text:
    tokens = texto.split()
    linea_entero = [indicepalabras[token] for token in tokens]
    train_text_int.append(linea_entero)

Mostrar parcialmente el nuevo contenido en train

In [101]:
train_text_int[:10]

[[1, 2, 3, 4, 5, 6, 7],
 [8, 9],
 [10, 11, 12],
 [13, 14, 15, 16, 17, 18],
 [19, 16, 4, 20, 4, 21],
 [22, 23, 24],
 [],
 [25, 26, 27, 28],
 [13, 29, 23, 30, 31, 32, 33, 34, 35, 36, 37],
 [13, 38, 39, 40, 41]]

In [102]:
for texto in test_text:
    tokens = texto.split()
    line_as_int = [indicepalabras.get(token, 0) for token in tokens]
    test_text_int.append(line_as_int)

Mostrar parcialmente el nuevo contenido en test

In [103]:
test_text_int[100:110]

[[757, 0, 16, 1357],
 [579, 22, 4, 691, 0],
 [33, 0, 0],
 [36, 1406, 55],
 [101, 0, 33, 318, 0],
 [45, 14, 1155, 55, 133, 0, 16, 0],
 [277, 0, 143, 13, 11, 0, 746, 0],
 [13, 0],
 [],
 [361, 38, 0, 615, 34, 603, 0]]

## Inicialización de los modelos

Creamos dos matrices de transicion, una para los archivos de Benedetti(clase 0), y el otro para Neruda(clase 1). Junto con la estructura(array) de las probabilidades.

### Clasificación de texto basado en un modelo de *Markov de primer orden*

Se crean dos conjuntos de matrices y vectores, uno para la clase 0 y otro para la clase 1.

**array_0 y array_1:** Son las futuras matrices de transición. array_0[i, j] almacenará la frecuencia con la que la palabra j aparece justo después de la palabra i en los textos de la clase 0.

**prob_et_0 y prob_et_1:** Son los futuros vectores de probabilidad inicial. prob_et_0[i] almacenará la frecuencia con la que la palabra i aparece al inicio de un texto de la clase 0.

**Punto clave: **Se inicializan con np.ones en lugar de ceros. Esta es una técnica de suavizado llamada Suavizado de Laplace (Laplace Smoothing). Sirve para evitar probabilidades de cero para secuencias de palabras que no aparecieron en el entrenamiento, lo que haría que el modelo fallara.

In [104]:
len_indicepalabras = len(indicepalabras)
array_0 = np.ones((len_indicepalabras, len_indicepalabras))
prob_et_0 = np.ones(len_indicepalabras)

array_1 = np.ones((len_indicepalabras, len_indicepalabras))
prob_et_1 = np.ones(len_indicepalabras)

In [105]:
array_0

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [106]:
prob_et_0

array([1., 1., 1., ..., 1., 1., 1.])

In [107]:
def compute_counts(text_as_int, A, pi):
    for tokens in text_as_int:
        last_idx = None
        for idx in tokens:
            # estamos en la primera palabra de la secuencia
            if last_idx is None:
                pi[idx] += 1
            else:
                A[last_idx, idx] += 1
            last_idx = idx

compute_counts([t for t, y in zip(train_text_int, Ytrain) if y == 0], array_0, prob_et_0)
compute_counts([t for t, y in zip(train_text_int, Ytrain) if y == 1], array_1, prob_et_1)

In [ ]:
# array_0
"""
array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])
"""

In [109]:
# Normaliza A y pi para que sean matrices de probabilidad válidas

array_0 /= array_0.sum(axis=1, keepdims=True)
prob_et_0 /= prob_et_0.sum()

array_1 /= array_1.sum(axis=1, keepdims=True)
prob_et_1 /= prob_et_1.sum()

In [ ]:
# prob_et_0
""" Output
array([0.00027226, 0.00027226, 0.00027226, ..., 0.00027226, 0.00054451,
       0.00027226])
       """

In [131]:
# array_0
"""
array([[0.00040161, 0.00040161, 0.00040161, ..., 0.00040161, 0.00040161,
        0.00040161],
       [0.00040161, 0.00040161, 0.00040161, ..., 0.00040161, 0.00040161,
        0.00040161],
       [0.00040161, 0.00040161, 0.00040161, ..., 0.00040161, 0.00040161,
        0.00040161],
       ...,
       [0.00040161, 0.00040161, 0.00040161, ..., 0.00040161, 0.00040161,
        0.00040161],
       [0.00040161, 0.00040161, 0.00040161, ..., 0.00040161, 0.00040161,
        0.00040161],
       [0.00040161, 0.00040161, 0.00040161, ..., 0.00040161, 0.00040161,
        0.00040161]])
        """

'\narray([[0.00040161, 0.00040161, 0.00040161, ..., 0.00040161, 0.00040161,\n        0.00040161],\n       [0.00040161, 0.00040161, 0.00040161, ..., 0.00040161, 0.00040161,\n        0.00040161],\n       [0.00040161, 0.00040161, 0.00040161, ..., 0.00040161, 0.00040161,\n        0.00040161],\n       ...,\n       [0.00040161, 0.00040161, 0.00040161, ..., 0.00040161, 0.00040161,\n        0.00040161],\n       [0.00040161, 0.00040161, 0.00040161, ..., 0.00040161, 0.00040161,\n        0.00040161],\n       [0.00040161, 0.00040161, 0.00040161, ..., 0.00040161, 0.00040161,\n        0.00040161]])\n        '

In [112]:
# Calcula el logaritmo de A y pi, ya que no necesitamos las probabilidades reales
log_array_0 = np.log(array_0)
log_prob_et_0 = np.log(prob_et_0)
log_array_1 = np.log(array_1)
log_prob_et_1 = np.log(prob_et_1)

In [113]:
log_prob_et_0

array([-8.20876405, -8.20876405, -8.20876405, ..., -8.20876405,
       -7.51561687, -8.20876405])

In [114]:
log_array_0

array([[-7.82003799, -7.82003799, -7.82003799, ..., -7.82003799,
        -7.82003799, -7.82003799],
       [-7.82003799, -7.82003799, -7.82003799, ..., -7.82003799,
        -7.82003799, -7.82003799],
       [-7.82003799, -7.82003799, -7.82003799, ..., -7.82003799,
        -7.82003799, -7.82003799],
       ...,
       [-7.82003799, -7.82003799, -7.82003799, ..., -7.82003799,
        -7.82003799, -7.82003799],
       [-7.82003799, -7.82003799, -7.82003799, ..., -7.82003799,
        -7.82003799, -7.82003799],
       [-7.82003799, -7.82003799, -7.82003799, ..., -7.82003799,
        -7.82003799, -7.82003799]])

In [115]:
count0 = sum(y == 0 for y in Ytrain)  # Cuenta de etiquetas de clase 0 en Ytrain
count1 = sum(y == 1 for y in Ytrain)  # Cuenta de etiquetas de clase 1 en Ytrain
print(f"Etiquetas clase 0 {count0}")
print(f"Etiquetas clase 1 {count1}")

total = len(Ytrain)  # Cantidad total de ejemplos de entrenamiento
p0 = count0 / total  # Probabilidad a priori de clase 0
p1 = count1 / total  # Probabilidad a priori de clase 1
logp0 = np.log(p0)  # Logaritmo de la probabilidad a priori de clase 0
logp1 = np.log(p1)  # Logaritmo de la probabilidad a priori de clase 1
p0, p1  # Imprime las probabilidades a priori de ambas clases


Etiquetas clase 0 1248
Etiquetas clase 1 432


(0.7428571428571429, 0.2571428571428571)

Viendo el resultado se puede estimar que el dataset esta desequilibrado. Hay mayor probabilidad de la clase de 0

### La Clase Classifier

Es el "plano" o la "receta" para construir nuestro clasificador.

    __init__(self, logAs, logpis, logpriors): El Constructor

Se inicializa con los modelos ya entrenados.
- **logAs:** Las matrices de transición de log-probabilidades (```[log_array_0, log_array_1]```).

- **logpis:** Los vectores de log-probabilidades iniciales (```[log_prob_et_0, log_prob_et_1]```).

- **logpriors:** La log-probabilidad previa de cada clase (logp0, logp1), que representa qué tan común es cada clase en general.

    
    _compute_log_likelihood(self, input_, class_): El Motor de Probabilidad

Esta función es el núcleo del modelo. Calcula la log-verosimilitud (log-likelihood) de una secuencia de texto.

Responde a la pregunta: "Si asumimos que este texto pertenece a la clase_ X, ¿qué tan probable es esta secuencia de palabras según el modelo de lenguaje de esa clase?"

Lo hace sumando las log-probabilidades:

  - Empieza con la probabilidad de la primera palabra (logpi).

  - Luego, para cada palabra siguiente, suma la probabilidad de transición desde la palabra anterior (logA).

La suma se usa en lugar de la multiplicación porque se trabaja con logaritmos.

    predict(self, inputs): El Tomador de Decisiones

Este método toma una lista de textos (inputs) y predice la clase para cada uno.

Para cada texto, realiza el siguiente cálculo para cada clase posible (0 y 1):
        ```log(Posterior) = log(Likelihood) + log(Prior)```

Esto es una aplicación directa del teorema de Bayes en el espacio logarítmico:
        ```posteriors = [self._compute_log_likelihood(input_, c) + self.logpriors[c] ...] ```

Finalmente, np.argmax(posteriors) elige la clase que tuvo el valor de log-posterior más alto. Esa es la predicción final.

In [116]:
# contrucción de un clasificador
class Classifier:
    def __init__(self, logAs, logpis, logpriors):
        self.logAs = logAs
        self.logpis = logpis
        self.logpriors = logpriors
        self.num_class = len(logpriors) # número de clases

    def _compute_log_likelihood(self, input_, class_):
        logA = self.logAs[class_]
        logpi = self.logpis[class_]

        last_idx = None
        logprob = 0
        for idx in input_:
            if last_idx is None:
                # Es el primer token en la secuencia
                logprob += logpi[idx]
            else:
                # Calcula la probabilidad de transición de la palabra anterior a la actual
                logprob += logA[last_idx, idx]

            # Actualiza last_idx para la próxima iteración
            last_idx = idx

        return logprob

    def predict(self, inputs):
        predictions = np.zeros(len(inputs))
        for i, input_ in enumerate(inputs):
            # Calcula los logaritmos de las probabilidades posteriores para cada clase
            posteriors = [self._compute_log_likelihood(input_, c) + self.logpriors[c] \
                          for c in range(self.num_class)]
            # Elige la clase con la mayor probabilidad posterior como la predicción
            pred = np.argmax(posteriors)
            predictions[i] = pred
        return predictions

Intancia la clase, se crea un objeto clasificador funcional

El código usa el clasificador para hacer predicciones tanto en el conjunto de entrenamiento (train_text_int) como en el de prueba (test_text_int).

Luego calcula la precisión (accuracy) comparando las predicciones (Ptrain, Ptest) con las etiquetas verdaderas (Ytrain, Ytest).

El "Test acc" (precisión de prueba) es el indicador más importante, ya que te dice qué tan bien generaliza tu modelo a datos que nunca ha visto.

In [117]:
# Cada arreglo debe estar en orden ya que se asume que las clases indexan estas listas
clf = Classifier([log_array_0, log_array_1], [log_prob_et_0, log_prob_et_1], [logp0, logp1])

In [118]:
Ptrain = clf.predict(train_text_int)
print(f"Train acc: {np.mean(Ptrain == Ytrain)}")

Train acc: 0.9803571428571428


In [119]:
Ptest = clf.predict(test_text_int)
print(f"Test acc: {np.mean(Ptest == Ytest)}")

Test acc: 0.8547619047619047


----
Siguientes pasos

## Analizar los Errores

In [120]:
# Encuentra los índices donde el modelo se equivocó en el conjunto de prueba
misclassified_idx = np.where(Ptest != Ytest)[0]

# Muestra uno de los errores
i = misclassified_idx[0]
print(f"Texto original (índices): {test_text_int[i]}")
print(f"Predicción: {Ptest[i]}, Real: {Ytest[i]}")
# (Necesitarías un diccionario inverso para convertir los índices de vuelta a palabras)

Texto original (índices): [40, 63, 375, 327, 0, 133, 703, 1488, 160, 17, 192]
Predicción: 0.0, Real: 1


## Probar con Entradas Nuevas


In [124]:
def predecir_texto(texto):
  tokens = texto.lower().split()
  indices_frase = [indicepalabras[token] for token in tokens if token in indicepalabras]

  prediccion = clf.predict([indices_frase])
  print(f"La frase fue clasificada como: {prediccion[0]}")

In [128]:
frase_n = """Yo no lo quiero, Amada."""

frase_b = """aquellas palabras que siempre me llenaban"""

predecir_texto(frase_n)
predecir_texto(frase_b)


La frase fue clasificada como: 0.0
La frase fue clasificada como: 0.0
